version: '3.5'

services:
  front:
    build: ./app
    restart: always
    ports:
      - 80:3000
    volumes:
      - ./app/:/usr/src/
      - ./app/package.json:/usr/src/package.json
      - /usr/src/node_modules
    networks:
      - guibutch

networks:
  guibutch:
    name: guibutch
